### ISSUE TITLE
Investigate the possibility of using Stark

### ISSUE THREAD

**Issue by boolafish** [omisego/research#103]
What others have done: 
1. https://medium.com/@StarkWare/starkexchange-8045695b798
1. https://www.youtube.com/watch?v=-cd9Tf7C0Ik

ref #76

**Comment by madxor** [comment]
Relevant quotes from the above sources:

> Concrete Efficiency: For a given computation, the **STARK prover is at least 10x faster** than both the SNARK and Bulletproofs prover. The **STARK verifier is at least 2x faster** than the SNARK verifier and more than 10x faster than the Bulletproof verifier. As StarkWare continues to optimize STARKs these ratios will likely improve. However, a **STARK proof length is ~100x larger than the corresponding SNARK and ~20x larger than BulletProofs**.

> Current DEX: max out @ 50 DEX Txs/block (100-200k gas / DEX Ttx)
> StarkDEX: 30 DEX @ 5.5M gas (180k gas / StarkDEX tx)
> StarkDEX; 500 DEX @ 6.7M gas (13.3k gas / StarkDEX tx)
> StarkDEX: verification on-chain can be done for over 10K txs/block (800 gas / StarkDEX tx)

> StarkDEX Gas usage -> O(log(n))

> Constantly improving, above numbers should go down.

**Comment by madxor** [comment]
By separating the Prover from the Verifier StarkDEX claims to scale efficiently.

![image](https://user-images.githubusercontent.com/42608901/59597527-5bed1a80-90fa-11e9-8789-0aba01a467f2.png)

**Comment by madxor** [comment]
What are our numbers?

**Comment by paulperegud** [comment]
Closing this one to indicate it is not really viable. Please reopen if something changed.
