### ISSUE TITLE
Problems definition, description and conceptualization.

### ISSUE THREAD

**Issue by madxor** [omisego/research#111]
In the process of conceptualization and definition of the staking game, the following objectives have been specified:

https://docs.google.com/document/d/1yXYf6Z0z0eIvKxUn8Zfg3V0ReqQBPxaEglbvNyoFwE0/edit?usp=sharing

**Comment by slavamirovsky** [comment]
Let's make some operational comments in the document attached (Google Doc).
I suggest to keep more high-level decisions here (GitHub)

**Comment by madxor** [comment]
Document updated with high level mechanics description. Please have a look.

**Comment by madxor** [comment]
Document is ready so closing this issue.
