### ISSUE TITLE
plasma-cash merging/splitting transactions

### ISSUE THREAD

**Issue by kasima** [omisego/research#17]

**Comment by smartcontracts** [comment]
# Background
Plasma Cash was designed with unique, non-mergable, non-splittable tokens in mind. However, it's become evident that merging and splitting are useful constructions. [Some](https://ethresear.ch/t/plasma-cash-plasma-with-much-less-per-user-data-checking/1298/37) [attempts](https://ethresear.ch/t/plasma-cash-plasma-with-much-less-per-user-data-checking/1298/44) [have](https://ethresear.ch/t/plasma-cash-plasma-with-much-less-per-user-data-checking/1298/53) been made to design a version of Plasma Cash that allows for merging and splitting.

The main issue so far is that merging requires checking the transaction history for *every* coin being merged together. This can very quickly increase the size of the required non-existence proofs. It's possible that a construction using Bloom filters could make this more feasible. 


# Research Questions
- Are there any concise ways to prove that the histories of multiple coins are valid?
- Can we do some magic range proof stuff?
- Can Bloom filters help?
- Should we allow arbitrary merging/splitting or does a limited # of merge/splits make more sense?
- Do we really need merging/splitting at all?


# Resources
[Plasma Cash: Plasma with much less per-user data checking](https://ethresear.ch/t/plasma-cash-plasma-with-much-less-per-user-data-checking/1298)
[Notes on Plasma Cash + Bloom filters](https://github.com/omisego/research/pull/23)

**Comment by boolafish** [comment]
Should follow up with plasma cashflow or prime research instead as that become a better solution for non-fungible cash construction. Closing this.
