### ISSUE TITLE
Exchange integration design

### ISSUE THREAD

**Issue by kasima** [omisego/research#28]

**Comment by DavidKnott** [comment]
## Exchange integration design

The primary advantage of using the OMG Network at this stage is security with low transaction costs. 
Exchanges can build on top of the Tesuji Tesuji OMG Network using limited custodial settlement (LCS)- exchange only has custody of funds during order matching or non custodial settlment (NCS)- the exchange never has custody of funds. NCS is more secure but exchanges have the added responsiblity of ensuring order firmness.

Initially exchanges wishing to utilize the OMG Network will be dealt with on a case by case basis as we build out the tooling to smooth out the integration process.

## Components

### Libraries

The LCS will have user facing create order functionality which will prompt users to send the funds they want to trade to the centralized exchange.  LCS will also have exchange facing settle order functionality that'll allow exchanges to sign over custody back to the users after their order has been matcher or cancelled.

The NCS library will allow exchanges to create a blacklist and swap orders. The blacklist will be used to ban users that create orders but then fail to honor them once they've been matched.  Swap orders may either be placed instantly via a market maker or may sit in the order book until they're matched or cancelled.

We'll create an OMG Network block explorer library that'll plug into the Watcher and make it simple for anyone using the OMG Network to display the information they care about in the browser.

### Liquidity Provider
Given that LCS exchanges will already have custody of funds for a short amount of time LCS exchanges should also implement their own liquidity provider which will allow users to transfer custody of their funds to the exchange and then receive the same funds on Ethereum without having to wait the challenge period.

NCS exchanges have a harder choice to make and may want to wait until the OMG Network supports non-custodial atomic swaps with Ethereum to implement a liquidity provider.

### Exit protocol
Exchanges building a top the OMG Network will have to develop their own protocol for alerting their users to exit the OMG Netowrk within a timely manner.  Exchanges should use all information at their disposal to get their users to exit ranging from phone texts to tweets. 

### Block Explorer
We'll use the block explorer library to create an OmiseGO run block explorer for users who don't want to create there own front end.

**Comment by smartcontracts** [comment]
> The NCS library will allow exchanges to create a blacklist and swap orders. The blacklist will be used to ban users that create orders but then fail to honor them once they've been matched.

Does this still apply if we remove confirmations?

> Exchanges building a top the OMG Network will have to develop their own protocol for alerting their users to exit the OMG Netowrk within a timely manner. Exchanges should use all information at their disposal to get their users to exit ranging from phone texts to tweets.

This seems like an interesting design space for Plasma in general. It could be useful to come up with some best practices and utilities for alerting users of Plasma chain issues.

**Comment by pdobacz** [comment]
For the LCS, are we trying to explore ideas like [limited custody cex](https://github.com/omisego/docs/pull/2) to limit the exposure of the funds held in custody even more?

**Comment by kasima** [comment]
@kfichter:

> Does this still apply if we remove confirmations?

How would no-confs address funds being moved between the time the order is placed and matched?

**Comment by whoisjeremylam** [comment]
Whilst others can build any kind of exchange, I feel we should be promoting exchange integration that only has firm orders.

Orders that fail to settle erode confidence in the exchange. Given the low KYC requirements of most exchanges, it wouldn't be cumbersome to create a multiple accounts for the purposes of taking advantage of high volatility days.

Once we have decided on a model, I'd like for us to produce an `Exchange Integration Guide` whose audience are the devs on an exchange on how to integrate with Plasma.

Does it make sense to prescriptive as possible, even to the level of the protocol to place orders? This way there is a common protocol and API for users to place orders and be notified of events, such as when orders settle and when users need to exit from the chain. 

We don't need to overdo the protocol (and we could use an existing industry standard) but I think this would make it much clearer for exchanges what to do. Additionally, it would be possible for different client interfaces to be developed that work against different exchanges.

**Comment by kasima** [comment]
Let's focus the conversation on the near term ship and the LC++ design [here](https://github.com/omisego/docs/pull/2/files). Once we have that in place, we can revisit a more general integration guide. Does that seem fair to everyone?
