### ISSUE TITLE
Batch settlement proof

### ISSUE THREAD

**Issue by boolafish** [omisego/research#59]
# Note
This propose a "batch transaction submission" mechanism on Child Chain.
Hopefully this can provide a way to bind settlement with transactions for fee (exchange and network).
So we can fulfill the DEX MVP requirement F3:
> An exchange should be able to offer a pricing model that is decoupled from the network costs of using the OMG network

I would consider this as a subtask of #53 

Design doc: https://omisego.atlassian.net/wiki/spaces/RES/pages/25100330/Batch+Transactions+submission?atlOrigin=eyJpIjoiNDA4YTU4Y2Q3NGJiNDIyOWJiMTI2OTRiN2EzYTRkYTEiLCJwIjoiYyJ9

**Comment by boolafish** [comment]
As @pdobacz mentioned inside the doc, our TX is actually 4 inputs and outputs. The current proof design uses at most 3 outputs, which is quite likely to be enough. (However, if we need extra 2 slots for exchange fee + network fee then it still has the possibility to be insufficient)

But pumping (4, 4) to something larger is also an option on the table, which, might be a simpler option as this moment.

Though I think the idea of a batch settlement is interesting and useful. Close this first as I think the priority of using batch submission is low at this engineering cycle. Can revisit anytime in the future.

**Comment by boolafish** [comment]
Reopen as talked with @paulperegud seems like we would need this for this cycle:
1. We cannot chain txs in one block in MoreVp. In other words, if we have two consecutive settlements, the second one needs to wait at least one block finalization which is around 15 sec.
2. Auction settlement might be required for low liquidity market.

Some notes from the previous talk @2019.04.03:
- We don't need to stick with current Tesuji plasma design. We can add new tx type with large inputs/outputs and perhaps new data type for settlement.
- Data availability of exchange can be a duty of exchange like plasma operator. When data is not available, use "exit" to force the exchange to disclose data. 
- Investigate the idea of "settlement" data + merkle tree of orders on plasma. 
- Possibly use Merkle sum tree for settlement?

**Comment by pdobacz** [comment]
> if we have two consecutive settlements, the second one needs to wait at least one block finalization which is around 15 sec.

that is - only for a single order? Separate orders settle concurrently with no fuss, correct?

**Comment by boolafish** [comment]
@pdobacz yeah, independent orders have no issue!
I haven't really looked into this yet, but I recall this is the issue @paulperegud mentioned: https://github.com/omisego/docs/issues/22

**Comment by boolafish** [comment]
(For availability)
Me & Pepesza had a call and go through the design for batch settlement for ODEX. Following is the note doc: [ODEX proofs notes @ 2019.04.04](https://docs.google.com/document/d/1ftWqCFX_4QjA_KMU05MjTHfm8dVleB0NZgxI9sZLaiw/edit?ts=5ca5dff6)

**Comment by boolafish** [comment]
Putting WIP spec doc here for availability: https://hackmd.io/ox5XLjdPRK6N3Mp9T9eUZw?view

Would probably move the doc to here or the doc repo or wiki after finalized.

**Comment by boolafish** [comment]
Have a main draft as the doc above. Breaking remaining part into smaller stories.
