### ISSUE TITLE
Removing time limit of mass exit from 1 week

### ISSUE THREAD

**Issue by boolafish** [omisego/research#62]
Disclaimer: this is just me throwing Some idea. Not thoroughly thought yet.

### Problem
When mass exit happens, all output owner should start exit within 1 week.
This would limit our max num of UTXO to like around [some million levels](https://github.com/omisego/devops/issues/57#issuecomment-481997528). (num of max possible exit can be handled on ethereum within a week). Even we can merge utxo to mitigate this, assuming people only merges their own UTXO, this would implies we can at most have millions of users.

### Idea
Mass exit can happen and be forced to be done within a week when operator push invalid tx to a block, and start to exit that tx. We use priority queue to promise all valid tx can be exited before that. However, it need to be within a week, otherwise the invalid exit would successfully exit.

This can happen as we don't verify such invalid tx is invalid on chain. If we can flag such tx invalid, and block all further exit after that tx, we can extend the exit period. (As the invalid tx cannot exit anyway, people can slowly do their exit without worry)

So we can have a "flag invalid tx exist" function. This combines well as we are abstracting our contract. The abstract layer might be able to define games to prove invalid.

### Case 1
Operator exit the first invalid tx.
This is the case operator tries to exit the first invalid tx (double spend or not correctly signed or sum of output > sum of input). 
This exit can be easily canceled by run and verify the invalid part.

### Case 2
Operator exit a "seems like valid" tx that is chained from an invalid tx.
Someone must start a "flag invalid tx exists" function on chain and provide the first invalid tx he/she found. After such function finalized, the "seems like valid" exit would be blocked as it's behind the flagged tx. (All tx after flagged tx would be consider invalid, the only way to get out is IFE)

**Comment by pdobacz** [comment]
How would data availability be ensured?

Another topic to delve into would be: can the "chained transactions" game be played out fairly on the root chain, taking gas, incentives etc. into account? Intuitively, this feels like it would somehow boil down to effectively replicating the whole child chain's logic in the root chain contract.

**Comment by boolafish** [comment]
lol you're so right on data availability. So operator can withhold invalid tx and chain it and exit the chained one.

I guess playing the whole "chained transactions" would be way too complex like you mentioned, would probably bring the whole child chain to root chain lol.

Closing this issue as it is proven wrong.
