### ISSUE TITLE
Enable fast withdrawals from chain

### ISSUE THREAD

**Issue by paulperegud** [omisego/research#63]
We need to enable fast withdrawals from plasma chain, done with the help of external liquidity provider. That would help to remove friction for end users, greatly improving usability of the chain for payments. Source: talk with Kei Oda from Quantstamp.

Possible flow.
1) User starts an exit from the chain (standard exits only, for simplicity)
2) User calls external provider's API to request the swap, passing along the signature which confirms fast withdrawal fee.
3) Provider checks the state of the chain (makes sure that exit will not get challenged)
4) Provider calls smart contract, passing along the signature by the exit owner.
5) Contract transfers amount-fee to user, replaces `.owner` field of the exit with provider's address.

Things to minimize:
1) Risk of the liquidity provider (low risk is low fee, and we want a very low fee).
2) Time between `startStandardExit` and swap finalization.

Please also consider interaction between this feature and in-flight exits.

**Comment by boolafish** [comment]
some previous related doc: https://github.com/omisego/research/blob/master/plasma/simple_fast_withdrawals.md

**Comment by paulperegud** [comment]
Ok, I'm closing this one since it is inferior to old proposal by Kelvin.

**Comment by paulperegud** [comment]
New tracking issue: https://github.com/omisego/research/issues/64
