### ISSUE TITLE
Censorship protection

### ISSUE THREAD

**Issue by boolafish** [omisego/research#81]
## Description
**As a trader**, I want to be able to trade in a platform that I won't be censored.
**So that** I do not need to take the risk of losing money because of being censored and not able to make my transaction through by venue on purpose.

**As a venue** I want to show my platform is censorship protected,
**So that** I can attract more traders to the platform.

## Successful Criteria
- List protection ideas we have somewhere.
- Specifies the best idea might be able to use so far.

**Comment by boolafish** [comment]
[NOTE]
We do not stop venue from censoring a trader directly from protocol layer. However, a trader can prove that he/she is being censored on ethereum to make it obvious that such venue is dishonest, and possibly slash some bond of venue.

Since each batch settlement has a “settlement price”, the goal to prove censorship is by the followings:

1. your price is better than other orders in that settlement
1. your order is older than or the same age as other orders in that settlement
1. your order is never settled

In the first phase (this MVP spec) of DEX, orders are transparent on settlement. As a result, it is easy to prove that your order is actually a better and older ones then the others. To prove the order never being settled, it would need a interactive game to do that. Venue need to challenge with the inclusion proof of the order in certain settlement transaction.

How to do this on zk-snark settlement requires further research.

**Comment by whoisjeremylam** [comment]
> your order is older than or the same age

Time may not be the only way in which a venue may sort the priority in which orders are matched, especially when considering auctions.

What were we thinking the mechanism would look like for a trader demonstrate that their order is older?

**Comment by boolafish** [comment]
ah, it's more like which "round" your order starts (round number for batched auction, eg batch-1, batch-2, ....)
So if your order starts in round N, and for example in N+1 there's a settlement which your price is better but your order is not in then we might consider this a censorship.

**Comment by boolafish** [comment]
[NOTE]
In the idea of `Moving "Ordering" Responsibility out of Venue` in the front-running doc mitigates censorship issue as well: [Frontrunning doc](https://omisego.atlassian.net/wiki/spaces/RES/pages/37552167/Front+Running+Protection+Ideas)

**Comment by boolafish** [comment]
Might have good enough ideas already. closing this.
